#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           claw, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           liftRightMotor, tmotorVex269, openLoop)
#pragma config(Motor,  port6,           liftLeftMotor, tmotorVex269, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                    - Dual Joystick Control -                                      *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/
//+++++++++++++++++++++++++++++++++++++++++++++| VOID FUNCTIONS |+++++++++++++++++++++++++++++++++++++++++++++++
void forward() {
  		// forward
		motor[rightMotor] = 32;
		motor[leftMotor] = 30;
		wait1Msec(800);

		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
}

void turnleft90() {
	  // turns 90 degrees left
		motor[rightMotor] = 50;
		motor[leftMotor] = -50;
		wait1Msec(2800);

		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
}
void turnright90() {
		// turns right 90 degrees
		motor[rightMotor] = -50;
		motor[leftMotor] = 50;
		wait1Msec(2600);

		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
}
void reverse () {
	  // reverses
		motor[leftMotor] = -30;
		motor[rightMotor] = -32;
		wait1Msec(800);

		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
void liftclaw () {
  	// lifts claw
		motor(liftRightMotor) = 34;
  	motor(liftLeftMotor) = 34;
  	wait1Msec(500);

  	// stop lifting claw
  	motor(liftRightMotor) = 0;
  	motor(liftLeftMotor) = 0;
}
void lowerclaw() {
		// lower clow
		motor(liftRightMotor) = -18;
  	motor(liftLeftMotor) = -18;
  	wait1Msec (500);

  	motor(liftRightMotor) = 0;
  	motor(liftLeftMotor) = 0;
}
void openclaw() {
	// open clow
  	motor (claw) = -30;
		wait1Msec(1000);

		motor (claw) = 0;
}
void closeclaw() {
	// Close Clow
  	motor (claw) = 30;
		wait1Msec(1000);

		motor (claw) = 0;
}
void finish() {
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		motor(liftRightMotor) = 0;
  	motor(liftLeftMotor) = 0;
  	motor (claw) = 0;
}
void clawstop(){
		motor (claw) = 0;
	  motor (liftRightMotor) = 0;
	  motor (liftLeftMotor) = 0;
}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	int i = 0;

  while(1 == 1)
  {
    if (vexRT[Btn7U] == 1) { // claw up
    	liftclaw();
    }
		else if (vexRT[Btn7D] == 1) { // claw down
    	lowerclaw();
    }
		else if (vexRT[Btn7R] == 1) { // close claw
    	closeclaw();
    }
    else if (vexRT[Btn7L] == 1) { // open claw
    	openclaw();
    }
    else { // all them zeros if the above is not used.
  		clawstop();
  	}

    if (vexRT[Btn8U] == 1 && i == 0) { // forward short
			forward();
    }
    else if (vexRT[Btn8D] == 1 && i == 0) { // backward short
			reverse();
 		}
 		else if (vexRT[Btn8R] == 1 && i == 0) { // right short
 			turnright90();
 		}
 		else if (vexRT[Btn8L] == 1 && i == 0) { // left short
			turnleft90();
 		}
 		if (vexRT[Btn5U] == 1) {
  			i = 1;
  	}
  	if (vexRT[Btn5D] == 1) {
  			i = 0;
  	}
  	if (i == 1) {
	  	motor[leftMotor]  = vexRT[Ch3];   // Left Joystick Y value
  	  motor[rightMotor] = vexRT[Ch2];   // Right Joystick Y value
  	}

  	if (vexRT[Btn6D] == 1) {

  		forward();
  		forward();
  		turnright90();
  		openclaw();
  		forward();
  		closeclaw();
  		liftclaw();
  		reverse();
  		turnleft90();
  		forward();
  		forward();
  		lowerclaw();
  		openclaw();

  		//fullstop
  		finish();

  	}

	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
