#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           claw, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           liftRightMotor, tmotorVex269, openLoop)
#pragma config(Motor,  port6,           liftLeftMotor, tmotorVex269, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                    - Dual Joystick Control -                                      *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	int i = 0;

  while(1 == 1)
  {

    if (vexRT[Btn7U] == 1) { // klo upp
    	motor(liftRightMotor) = 34;
    	motor(liftLeftMotor) = 34;
    }
		else if (vexRT[Btn7D] == 1) { // klo nidur
    	motor(liftRightMotor) = -18;
    	motor(liftLeftMotor) = -18;
    }
		else if (vexRT[Btn7R] == 1) { //klo saman
    	motor(claw) = 30;
    }
    else if (vexRT[Btn7L] == 1) { // klo i sundur
    	motor(claw) = -30;
    }
    else {
    	motor (claw) = 0;
    	motor (liftRightMotor) = 0;
    	motor (liftLeftMotor) = 0;
  	}

    if (vexRT[Btn8U] == 1 && i == 0) { // forwards short
    	motor[rightMotor] = 40;
			motor[leftMotor]  = 40;
			wait1Msec(700);
			motor[rightMotor] = 0;
    	motor [leftMotor] = 0;
    }
    else if (vexRT[Btn8D] == 1 && i == 0) { // backwards short
    	motor[rightMotor] = -40;
    	motor [leftMotor] = -40;
    	wait1Msec(700);
			motor[rightMotor] = 0;
    	motor [leftMotor] = 0;
 		}
 		else if (vexRT[Btn8R] == 1 && i == 0) { // right short
    	motor[rightMotor] = -40;
    	motor [leftMotor] = 40;
    	wait1Msec(1000);
			motor[rightMotor] = 0;
    	motor [leftMotor] = 0;
 		}
 		else if (vexRT[Btn8L] == 1 && i == 0) { // left short
    	motor[rightMotor] = 40;
    	motor [leftMotor] = -40;
    	wait1Msec(1000);
			motor[rightMotor] = 0;
    	motor [leftMotor] = 0;
 		}
 		if (vexRT[Btn5U] == 1) {
  			i = 1;
  	}
  	if (vexRT[Btn5D] == 1) {
  			i = 0;
  	}
  	if (i == 1) {
	  	motor[leftMotor]  = vexRT[Ch3];   // Left Joystick Y value
  	  motor[rightMotor] = vexRT[Ch2];   // Right Joystick Y value
  	}

  	if (vexRT[Btn6D] == 1) {
  		// forward
  		motor[rightMotor] = 40;
  		motor[leftMotor] = 40;
  		wait1Msec(700);
  		// turns right
  		motor[rightMotor] = -30;
  		motor[leftMotor] = 40;
  		wait1Msec(300);
  		// stops turning
  		motor[rightMotor] = 0;
  		motor[leftMotor] = 0;
  		// opens claw
  		motor (claw) = -30;
  		wait1Msec(30);
  		// drives forward in a short time
  		motor[rightMotor] = 30;
  		motor[leftMotor] = 30;
  		wait1Msec(30);
  		// stops driving in a short time
  		motor[rightMotor] = 0;
  		motor[leftMotor] = 0;
  		wait1Msec(1);
  		// closes claw
  		motor[claw] = 30;
  		wait1Msec(50);

  	}
    if (vexRT[Btn6U] == 1) {
    	motor[rightMotor] = 0;
    	motor [leftMotor] = 0;
 		}

  }

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
